# Generated by Django 6.1.1 on 2026-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
